# Generated by Django 2.2 on 2021-07-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_created_by',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
