# Generated by Django 2.2 on 2021-07-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_auto_20210724_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
