# Generated by Django 2.2 on 2021-07-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_posts', to='dashboard_app.User'),
        ),
    ]
